### PR TITLE
perf!: replace `execa` with `tinyexec`

### LINKED ISSUE #150: Replace `execa` with `tinyexec`
### Describe the feature

This is a suggestion to replace heavier [`execa`](https://pkg-size.dev/execa) with a lighter [`tinyexec`](https://pkg-size.dev/tinyexec) to reduce the dependency count and the bundle size.

### Additional information

- [x] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by ziebam**
Resolves #150.

This PR is a suggestion to replace heavier [`execa`](https://pkg-size.dev/execa) with a lighter [`tinyexec`](https://pkg-size.dev/tinyexec) to reduce the dependency count and the bundle size.

### CODE REVIEW

**Comment by ziebam** [comment]
Actually, since there are only two usages, we could just use `node:child_process` directly. What do you think?

**Comment by pi0** [comment]
Thanks for PR. I think so we might directly use `node:child_process`.

Nypm was doing this before. We moved to execa to support cross-platform search path of `corepack` mainly (https://github.com/unjs/nypm/pull/54). However with Node.js not going to ship corepack by default.. i think we might change strategy altogether. 

Since this change might introduce regression, i am thinking more about options we have.

**Comment by ziebam** [comment]
> Thanks for PR. I think so we might directly use `node:child_process`.
> 
> Nypm was doing this before. We moved to execa to support cross-platform search path of `corepack` mainly (#54). However with Node.js not going to ship corepack by default.. i think we might change strategy altogether.
> 
> Since this change might introduce regression, i am thinking more about options we have.

No rush! No matter which solution you decide on, I'm happy to help driving this replacement forward.

**Review by pi0 — APPROVED** [review]
Let's do it for nypm 0.4.x in meantime!

**Pull request merged**
