### PR TITLE
feat: `upgradeDependency` utility

### LINKED ISSUE #78: `upgradeDependency` utility
This util should:
- Detect current dependency version constraints (semver major, minor) and it's devDependency/dependency status
- Use proper package manager command to make sure in required constraint it is latest
- Allow overriding to make a minor/major bump

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #78

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Not sure how I missed adding those deps 😅

Thanks for taking the time on fixing these...

**Comment by pi0** [comment]
Thanks for PR dear @rishi-raj-jain. I have made few more refactors (it is halfway done sorry in between projects). I think this is a really good start. Will followup later.

**Comment by rishi-raj-jain** [comment]
> Thanks for PR dear @rishi-raj-jain. I have made few more refactors (it is halfway done sorry in between projects). I think this is a really good start. Will followup later.

Awesome! Do let me know if I can contribute. I think nypm shall also have like each function to do things, addDep, checkDep, updateDep, etc. But yeah ik the time is limited

**Comment by pi0** [comment]
Hi and thanks for this PR again. I think it might be better to rethink about this functionality after introducing `getPackageInfo` (https://github.com/unjs/nypm/issues/7) and working with other registries.

**Pull request closed without merging**
